server_name: n3
port: 4222
http_port: 8222

jetstream {
  store_dir: "/data"
  max_mem_store: 256MB
  max_file_store: 2GB
}

cluster {
  name: "pi-cloud-spike"
  port: 6222
  routes: [
    nats-route://nats-1:6222
    nats-route://nats-2:6222
  ]
}
