import type { Database } from "@pi-cloud/database";
import { SessionError } from "@earendil-works/pi-agent-core";
import { sql, type Insertable, type Transaction } from "kysely";
import { committedItemSequence, type PiCommittedItem } from "./session-mutation.ts";

/** Apply acknowledged, fully stamped native records. The caller co-commits its
 * Kafka position and execution boundary in this transaction. No sequence, ID,
 * parent or timestamp is generated by this projection. */
export async function projectNativeSessionAppend(
  transaction: Transaction<Database>,
  input: {
    tenantId: string;
    sessionId: string;
    appendId: string;
    items: readonly PiCommittedItem[];
  },
): Promise<void> {
  const { tenantId, sessionId, appendId, items } = input;
  if (!items.length) return;
  const session = await transaction
    .selectFrom("pi_sessions")
    .select("next_seq")
    .where("tenant_id", "=", tenantId)
    .where("id", "=", sessionId)
    .forUpdate()
    .executeTakeFirstOrThrow();
  const prior = await transaction
    .selectFrom("pi_session_log")
    .select("seq")
    .where("tenant_id", "=", tenantId)
    .where("session_id", "=", sessionId)
    .where("append_id", "=", appendId)
    .executeTakeFirst();
  if (prior) {
    if (Number(prior.seq) !== committedItemSequence(items.at(-1)!))
      throw new SessionError("storage", "Native append identity changed sequence");
    return;
  }
  const first = Number(session.next_seq);
  for (const [index, item] of items.entries()) {
    if (!Number.isSafeInteger(first + index) || committedItemSequence(item) !== first + index)
      throw new SessionError("storage", "Native Session append is not contiguous");
  }
  const rows = await transaction
    .selectFrom("pi_session_lanes")
    .select(["lane", "leaf_id"])
    .where("tenant_id", "=", tenantId)
    .where("session_id", "=", sessionId)
    .execute();
  const heads = new Map(rows.map((r) => [r.lane, r.leaf_id]));
  const created = new Set<string>(),
    changed = new Set<string>();
  const ids = items.flatMap((item) =>
    item.kind === "entry" ? [item.entry.id] : item.kind === "record" ? [item.record.id] : [],
  );
  if (new Set(ids).size !== ids.length)
    throw new SessionError("already_exists", "Native append reuses an ID");
  if (ids.length) {
    const collision = await sql<{ found: boolean }>`select exists(
      select 1 from pi_session_visible_entries where tenant_id=${tenantId}::uuid
        and session_id=${sessionId} and id=any(${ids}::text[])
      union all select 1 from pi_session_records where tenant_id=${tenantId}::uuid
        and session_id=${sessionId} and id=any(${ids}::text[])
    ) as found`.execute(transaction);
    if (collision.rows[0]?.found)
      throw new SessionError("already_exists", "Native append reuses an ID");
  }
  const targets = items.flatMap((item) =>
    item.kind === "lane" && item.leafId
      ? [item.leafId]
      : item.kind === "fact" && item.fact === "label"
        ? [item.targetId]
        : [],
  );
  const known = new Set(
    targets.length
      ? (
          await transaction
            .selectFrom("pi_session_visible_entries")
            .select("id")
            .where("tenant_id", "=", tenantId)
            .where("session_id", "=", sessionId)
            .where("id", "in", targets)
            .execute()
        ).map((r) => r.id)
      : [],
  );
  const entries: Insertable<Database["pi_session_entries"]>[] = [];
  const records: Insertable<Database["pi_session_records"]>[] = [];
  const logs: Insertable<Database["pi_session_log"]>[] = [];
  const labels = new Map<string, { label: string | undefined; seq: number }>();
  let name: string | undefined;
  for (const item of items) {
    const seq = committedItemSequence(item);
    let payload: Record<string, unknown>;
    if (item.kind === "entry") {
      const e = item.entry;
      if (!heads.has(item.lane) || heads.get(item.lane) !== e.parentId)
        throw new SessionError("storage", "Native Entry parent differs from its Lane head");
      known.add(e.id);
      heads.set(item.lane, e.id);
      changed.add(item.lane);
      entries.push({
        tenant_id: tenantId,
        session_id: sessionId,
        id: e.id,
        seq,
        parent_id: e.parentId,
        type: e.type,
        custom_type: e.type === "custom" ? e.customType : null,
        timestamp_ms: e.timestamp,
        payload: e as unknown as Record<string, unknown>,
        turn_id: item.turnId,
      });
      payload = { lane: item.lane, turnId: item.turnId, entry: e };
    } else if (item.kind === "record") {
      const r = item.record;
      if (!heads.has(r.lane))
        throw new SessionError("invalid_lane", "Native Record Lane is missing");
      records.push({
        tenant_id: tenantId,
        session_id: sessionId,
        id: r.id,
        seq,
        lane: r.lane,
        type: r.type,
        run_id: r.type === "operation_started" ? r.id : "runId" in r ? (r.runId ?? null) : null,
        operation_kind: r.type === "operation_started" ? r.intent.kind : null,
        timestamp_ms: r.timestamp,
        payload: r as unknown as Record<string, unknown>,
        turn_id: item.turnId,
      });
      payload = { turnId: item.turnId, record: r };
    } else if (item.kind === "lane") {
      if (item.leafId !== null && !known.has(item.leafId))
        throw new SessionError("invalid_entry", "Native Lane target is missing");
      if (item.create === heads.has(item.lane))
        throw new SessionError(
          "invalid_lane",
          "Native Lane creation/movement does not match storage",
        );
      if (item.create) created.add(item.lane);
      heads.set(item.lane, item.leafId);
      changed.add(item.lane);
      payload = { lane: item.lane, leafId: item.leafId };
    } else if (item.fact === "name") {
      name = item.name;
      payload = { fact: "name", name };
    } else {
      if (!known.has(item.targetId))
        throw new SessionError("invalid_entry", "Native Label target is missing");
      labels.set(item.targetId, { label: item.label, seq });
      payload = {
        fact: "label",
        targetId: item.targetId,
        ...(item.label === undefined ? {} : { label: item.label }),
      };
    }
    logs.push({
      tenant_id: tenantId,
      session_id: sessionId,
      seq,
      kind: item.kind,
      payload,
      append_id: null,
    });
  }
  logs.at(-1)!.append_id = appendId;
  if (entries.length) await transaction.insertInto("pi_session_entries").values(entries).execute();
  if (created.size)
    await transaction
      .insertInto("pi_session_lanes")
      .values(
        [...created].map((lane) => ({
          tenant_id: tenantId,
          session_id: sessionId,
          lane,
          leaf_id: heads.get(lane)!,
        })),
      )
      .execute();
  if (records.length) await transaction.insertInto("pi_session_records").values(records).execute();
  await transaction.insertInto("pi_session_log").values(logs).execute();
  if (changed.size)
    await sql`update pi_session_lanes target set leaf_id=head.id
    from jsonb_to_recordset(${JSON.stringify([...changed].map((lane) => ({ lane, id: heads.get(lane) })))}::jsonb) head(lane text,id text)
    where target.tenant_id=${tenantId}::uuid and target.session_id=${sessionId} and target.lane=head.lane`.execute(
      transaction,
    );
  for (const [targetId, value] of labels) {
    if (value.label === undefined)
      await transaction
        .deleteFrom("pi_session_labels")
        .where("tenant_id", "=", tenantId)
        .where("session_id", "=", sessionId)
        .where("target_id", "=", targetId)
        .execute();
    else
      await transaction
        .insertInto("pi_session_labels")
        .values({
          tenant_id: tenantId,
          session_id: sessionId,
          target_id: targetId,
          label: value.label,
          updated_seq: value.seq,
        })
        .onConflict((c) =>
          c
            .columns(["tenant_id", "session_id", "target_id"])
            .doUpdateSet({ label: value.label!, updated_seq: value.seq }),
        )
        .execute();
  }
  await transaction
    .updateTable("pi_sessions")
    .set({ next_seq: first + items.length, ...(name === undefined ? {} : { name }) })
    .where("tenant_id", "=", tenantId)
    .where("id", "=", sessionId)
    .execute();
  const recoveries = items.flatMap((item) =>
    item.kind === "entry" && item.recoveryId ? [item.recoveryId] : [],
  );
  if (recoveries.length)
    await transaction
      .updateTable("session_terminal_events")
      .set({ interrupted_prefix: null })
      .where("tenant_id", "=", tenantId)
      .where("event_id", "in", recoveries)
      .execute();
}
